### ISSUE TITLE
fence gates make the opening and closing sound twice when opened or closed

### ISSUE THREAD

**Issue by ghost** [LO6AN/New-Frontier-Craft#72] opened 2021-09-14 12:10 UTC
https://user-images.githubusercontent.com/67587410/133255118-f91ddca5-66e1-4807-a73a-c6ab01b28e45.mp4

**Comment by ghost** [comment] 2021-09-14 12:11
and for some reason i just can't get video to show up when uplouding it to this site, but when you download it you'll be able to see footage.

**Comment by VivianTheFox** [comment] 2021-11-22 19:16
Moved this over to client. The issue is that the client and server are both telling the client to play the sound whenever opening the gate. However, when the server does it, all players can hear it. The client can only hear what the client can hear. So the proper fix to this is making it so the client doesn't try playing its own sound effect over the server one while in multiplayer. Meaning this'll be fixed in v3.5.0, as we have no plans to release a v3.4.1_02 or anything like that.

**Comment by Roadhog360** [comment] 2021-11-23 17:13
Can also be fixed by using the function I made in the server code to play a sound to every player except the one who used the gate.

**Comment by VivianTheFox** [comment] 2021-12-29 23:39
Forgot to close this one, as it was fixed with the v3.4.1_02 build of the server

**Closed as completed by VivianTheFox** 2021-12-29 23:39 UTC
Labels: Client, Low Priority
