### ISSUE TITLE
problems with textures(nfc v3.4.2)

### ISSUE THREAD

**Issue by Genudza** [LO6AN/New-Frontier-Craft#100] opened 2023-04-07 13:16 UTC
Hello
I caught a bug.
I do not load textures of blocks

Всем привет
я словил баг(глюк)
У меня не грузятся текстуры блоков

![image](https://user-images.githubusercontent.com/90350827/230614543-d3631bce-73dd-4008-848f-5dc4785e9415.png)

![image](https://user-images.githubusercontent.com/90350827/230615269-37258907-af5b-4391-9cbf-d88e63ff0285.png)

![image](https://user-images.githubusercontent.com/90350827/230615315-5602ab66-f953-49f0-b751-83737eafa2f9.png)

**Comment by ToufouMaster** [comment] 2023-04-09 21:14
i'm not developing anymore on the project, but i still can ask some precision to help those who work on it.

have you already tried to disable mods one by one? if you are able to give us the mod that make this mess, maybe they could solve this issue easier and faster.

Thanks for the Issue.

**Comment by ToufouMaster** [comment] 2023-04-09 21:16
Here is the solution:
![image](https://user-images.githubusercontent.com/68186078/230796867-4e1bc4f7-05e8-49dd-a593-92433db3657b.png)

**Comment by Roadhog360** [comment] 2023-10-07 05:10
Duplicate of #99

**Closed as not planned by Roadhog360** 2023-10-07 05:10 UTC
